preset: psr2

enabled:
    - remove_leading_slash_use
    - single_array_no_trailing_comma
    - spaces_before_semicolon
    - unused_use
    - concat_with_spaces
    - whitespacy_lines
    - ordered_use
    - remove_lines_between_uses
    - single_quote
    - duplicate_semicolon
    - extra_empty_lines
    - phpdoc_no_package
    - phpdoc_scalar
    - no_empty_lines_after_phpdocs
    - short_array_syntax
    - array_element_white_space_after_comma
    - function_typehint_space
    - hash_to_slash_comment
    - no_empty_comment
    - join_function
    - lowercase_cast
    - namespace_no_leading_whitespace
    - native_function_casing
    - no_empty_statement
    - self_accessor
    - short_bool_cast
    - unneeded_control_parenthese

finder:
  name:
    - "*.php"
  not-path:
    - ".Build"
    - "Documentation"
    - "Libraries"